# Generated by Django 2.0.5 on 2018-06-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('storage_capacity', models.IntegerField()),
                ('terminal_capacity', models.IntegerField()),
                ('combinations', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
